baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Jinyang Liu (刘锦阳)'
theme = "astatine"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    category = "categories"  
    tag = "tags"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = -150

# Make the tags and categories pages accessible directly from the navbar.
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = -130

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """I am a PhD student studying at the University of Copenhagen."""
    # Author of the site
    authorName = "Jinyang Liu (刘锦阳)"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "img/main.jpg"
        # Add an alt description for the image
        alt = "Profile picture"

    # Indicate if you host Katex yourself. Defaults to using the CDN KaTex.
    # hostedKaTex = false

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@Jack_harkness"
    # [params.mastodon]
        # name = "@jkharkness"
        # host = "mastodon.social"
    
    # Enable link to feed in footer
    blogrss = true

    # Enable pingback and webmention via webmention.io
    # webmention = "hugocisneros.com"


